telegram_token: <your telegram token>
gemini_api_key: <your gemini api key>
provider_token: <your provider token>
allowed_telegram_usernames: []  # if empty, the bot is available to anyone

# MySQL configuration
mysql_host: localhost
mysql_user: root
mysql_password: your_password
mysql_database: chatgpt_telegram_bot
